language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install karma
  - npm install karma-mocha --save-dev
  - npm install karma-coverage --save-dev

script:
  - karma start --reporters dots --browsers Firefox,PhantomJS --single-run
